hexlet-rus/runit

- app/javascript/index.jsx
- package-lock.json
- package.json
runit #19 
Добавляет базовую поддержку Sentry SDK в проект. При инициализации Sentry нужно было указать dsn, для этого я завёл аккаунт на sentry.io и там получил dsn. Сделал проверку работоспособности как указано в [документации](https://docs.sentry.io/platforms/javascript/guides/react/) всё получилось, ошибка попала во вкладку Issues в аккаунте sentry.io. 
Для правильной работы в runit нужно добавить dsn в переменные окружения и должно заработать.
> Added sending errors via sentry

- views/landing/landing-editor.pug
- webpack.config.js
Поменял путь на "/editor", открывается страница создания сниппета. Но без авторизации ничего не дает печатать так и должно быть? Или я что то не так сделал?
> Изменить путь у кнопки "Начать кодить"

- frontend/src/Pages/Profile.jsx
Была проблема, что не работает кнопка "Скопировать ссылку" на странице "Профиль".
Проблема решена. Теперь при нажатии на "Скопировать ссылку" URL страницы копируется в буфер обмена.
> Added Copy URL to Profile, Issue #186

- backend/src/users/dto/create-user.dto.ts
- backend/src/users/dto/update-user.dto.ts
- frontend/src/components/Modals/EditProfile.jsx
- frontend/src/components/Modals/SignUp.jsx
**Ссылка: https://supersnowsnail-runit.onrender.com/**
Привёл валидацию имени пользователя в модалке редактирования профиля к требуемому виду, аналогично #243.
Заодно пофиксил тот же самый баг в модалке регистрации (которая выпадает, если попробовать поделиться сниппетом, будучи незалогинненым, см. скрин).
Бага там было сразу два: собственно, сама валидация, а также то, что у поля для логина был name="name" вместо name="login", из-за чего из формы отсылались неверные данные и сервер возвращал 400 ошибку. По итогу поле логина переделал по аналогии с тем же полем в frontend/src/Pages/SignUp.jsx (кстати, ещё опечатку поправил в catch валидации модалки, там 409 ошибку ловило, поставил 400 по аналогии с frontend/src/Pages/SignUp.jsx).
Ещё, помимо прочего, обнаружил ошибку в валидации на …
> [#248] Fix login validation bug in modals

- backend/src/users/dto/create-user.dto.ts
- frontend/src/Pages/SignUp.jsx
- frontend/src/locales/en.js
- frontend/src/locales/ru.js
Теперь при попытке ввести уже занятый логин под полем логина будет отображаться сообщение о недоступности логина (так же, как отображаются сообщения об ошибках валидации). То же самое при использовании уже зарегистрированной почты.
В коде сервера поправлены ответы сервера при невозможности регистрации. Сервер отдает json той же структуры, что и раньше, но в поле `messsage` теперь не массив сообщений об ошибках(`'Пользователь уже существует!'`), а массив с кодами (`'loginIsUsed'`, `'emailIsUsed'`), которые можно обработать на клиенте.
> Fix SignUp form hints about the login or email used

- README.md
- README.ru.md
1. Добавил ссылку на Yarn 1 (Classic), чтобы было понятно, что в проекте используется именно эта версия, а не 2+.
2. Убрал Heroku CLI из системных требований (так как в тексте ниже приводится инструкция для деплоя на render.com).
> Обновлены системные требования в readme

- frontend/src/locales/en.js
- static.json
Погуглил и, кажется, чтобы heroku начал делать redirect с http к https, ему об этом надо сказать, поэтому добавил файлик static.json с полем https_only: true
> #303 http to https redirect

- frontend/src/components/Modals/Modal.jsx
- frontend/src/components/Modals/SnippetUnavailable.jsx
- frontend/src/components/SnippetButton/index.jsx
- frontend/src/locales/en.js
- frontend/src/locales/ru.js
Этот ПР относится к #287 
Пока что сделал заглушку в виде модалки с надписью что сниппет недоступен или удалён после её закрытия пользователя редиректит на домой. В идеале должен быть ответ с сервера с соответствующим кодом чтобы можно было использовать его для модалки или редеректа.
> Fix: #287 Show Snippet Unavailable Dialog and navigate user to home page if snippet has been deleted

- backend/src/auth/auth.service.ts
- frontend/src/components/Forms/GithubSignInButton.jsx
После обновления дизайна форм входа и регистрации при нажатии на кнопку входа через Гитхаб ничего не происходило
1. Переделал `button` в `a` Добавил ссылку на авторизацию.
2. Обновил редирект на сервере.
По второму пункту посоветуйте (отдельным коммитом сделал). Ссылка-редирект там была захардкодена и сейчас тоже осталось. Может как-то можно сделать, чтобы фронт уведомлял бэк, куда перебрасывать юзера?
При логине с формы логина перебрасывать на профиль — это ок. Но у нас есть сценарий, когда юзер регистрируется при просмотре сниппета через модалку. Там бы его перебрасывать назад на этот сниппет. А его перебросят на профиль — это не ок.
> Fix GitHub OAuth button

- frontend/src/utils/validationSchemas.js
Пробельный символ был не разрешен для имени сниппета.
Было:
Стало:
> [#379] added a space-symbol to validationSchemas.js/snippetName

- frontend/src/slices/languagesSlice.js
убрала в languagesSlice.js из state.supportedLanguages - php, python.
было: 4 поддерживаемых языка
стало: 2 поддерживаемых языка
> #401 deleted php and python from supported-languages

- frontend/src/pages/about/Faq.module.css
FAQ: при открытии аккордеона цвет header менялся на active-color. Я перезаписала этот active-color на white и убрала замену цвета before:иконки. 
Было: 
Стало:
> #410 changed --bs-accordion-active-color to white

- backend/src/users/dto/update-user.dto.ts
- frontend/src/components/Forms/UpdateAccountForm.jsx
Ошибки обновления пользовательских данных в личном кабинете теперь отображаются. 
деплой: https://heaven-tonight-runit-account-form.onrender.com
Можно зайти под (чтобы не регаться): 
test@mail.ru 
ert645qw
А данные ЛК менять на:
test2
test2@mail.ru
> fixed display of errors when user change account data

- frontend/src/components/Modals/RemoveAccount.jsx
- frontend/src/components/Modals/index.jsx
- frontend/src/locales/ru.json
- frontend/src/pages/settings/index.jsx
- frontend/src/routes.js
implement remove account
Render deploy: https://bobronaud-runit.onrender.com
> closed #419

- frontend/src/locales/en.json
- frontend/src/pages/landing/index.jsx
После мержа нового лэндинга, в котором изменился [locales/ru](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2Fbobronaud%2Frunit%2Fcommit%2Fd8eeb63584872096ae5f9fb2a2482ca098cff4ab%23diff-1b1a51fe9466ee16b644fc148d1f09fd766e1bb7dc73e0357cb83c44200b40e7L167) приходит объект вместо [ожидаемой строки](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2Fbobronaud%2Frunit%2Fblob%2Fmain%2Ffrontend%2Fsrc%2Fpages%2Flanding%2Findex.jsx%23L49)
Собственно я это дело пофиксил и для консистентности изменил [locales/en](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2Fbobronaud%2Frunit%2Fblob%2Fmain%2Ffrontend%2Fsrc%2Flocales%2Fen.json%23L167)
Render деплой: https://bobronaud-runit.onrender.com/
Как выглядит баг: <img width="1052" alt="image" …
> FIX BUG: landing header

- frontend/src/pages/about/Faq.jsx
- frontend/src/pages/about/Faq.module.css
- frontend/src/pages/about/index.jsx
- frontend/src/pages/landing/index.jsx
- frontend/src/pages/license-agreement/index.jsx
Пофиксил баг с переключением светлой темы на некоторых страницах.
1. Определения классов "bg-dark и text-white" в компонентах мешало переключению темы.
2. Удалил переназначение цвета css стилей аккордеона, что также мешало для работы светлой темы
3. Svg иконка в аккордеоне подгружалась в фиксированном белом цвете, заменил её на прописной знак "^", чтобы он мог менять цвет при переключении темы.
Render деплой: https://bobronaud-runit.onrender.com/
> closed #365

- frontend/src/components/Footer/index.jsx
- yarn.lock
Выровнял футер по центру, чтобы он соответствовал общему дизайну страницы. Адаптивность сохранена.
> [#435] center footer to look the same as hole page

- frontend/src/assets/stylesheets/application.scss
- frontend/src/assets/stylesheets/min-w.scss
- frontend/src/pages/snippet/FileToolbar.jsx
fixes https://github.com/hexlet-rus/runit/issues/407
1. Удалил класс у инпута, чтобы 'карандаш' был рядом с именем сниппета.
2. Для тултипа добавлен новый класс, чтобы корректно отображалась предупреждающая ошибка.
Класс для тултипа добавлен как новая утилита utilities API в scss/_utilities.scss, потом можно расширить значения и переиспользовать по необходимости.
> [#407] Update the snippet toolbar view

- frontend/src/pages/landing/Header.jsx
- frontend/src/pages/landing/landing.scss
https://github.com/hexlet-rus/runit/issues/453 вношу изменения по этому ишью
Сделал простое решение добавив пару классов бутстрапа на разных разрешениях. Немного отображение элементов в коллапсе. Поставил их слева, чтобы они смотрелись более гармоничнее
> fixed 992px header size collapse issue #453

- frontend/src/pages/landing/Landing.jsx
- frontend/src/pages/landing/landing.scss
Исправил отступы внутренние и внешние в секции, где указаны удобства сервиса на лендинге.
Было:
Стало:
> Fix margins in landing

- frontend/src/pages/landing/Faq.jsx
- frontend/src/pages/landing/Landing.jsx
Change the method of checking
the active theme page in Faq.jsx
Fix misspell clssaName to className
in Langing.jsx
> Fix bug #462

- frontend/src/components/Modals/NewSnippet.jsx
- frontend/src/pages/profile/NewSnippetForm.jsx
#469 решение проблемы со расширением сниппета при его создании
> fixed html extension when making new snippet

- frontend/src/utils/validationSchemas.js
пофиксил возможность создавать сниппеты с пустым именем
ишьюс - https://github.com/hexlet-rus/runit/issues/476
> Close #476

- frontend/src/components/Loaders/DefaultLoader.jsx
- frontend/src/locales/ru.json
Исправлен перевод спиннера загрузки по умолчанию. Ранее был текст appStatus.loading, сейчас отображает корректные перевод на 2 языках.
> fixed appStatus translation

- frontend/src/components/Footer/index.jsx
- frontend/src/pages/landing/Footer.jsx
now the link to the Non-Commercial License Agreement is available in both English and Russian versions
> [#517] fixed the disappearance of the footer link in the en version

- frontend/src/pages/snippet/index.jsx
In the HTML snippet, when switching to the dark theme, the browser background now remains white instead of becoming dark. Video below for reference.
https://github.com/user-attachments/assets/9099d6e5-bfc2-4c12-8f98-00d257b92950
> [#524]: fixed HTML snippet browser background color in dark theme

- frontend/src/locales/en.json
Added translation of the "Confirm" button in the form for duplicating the snippet when switching to English
> [#549]: Correction of translation of the "Confirm" button when switching to English

- frontend/src/components/Forms/SignInForm.jsx
- frontend/src/components/Navigation/GuestMenu.jsx
ProfileActionButtons localization for GuestUserMenu fixed.
Additionally, fixed the button display on the Sign-In form, which appeared misaligned in English.
Before:
After:
Deploy: https://mad-chameleon-runit.onrender.com
> [#553] fixed guestMenu localization bug

- frontend/src/pages/profile/SnippetCardWrapper.jsx
- frontend/src/utils/genDuplicateSnippetName.js
Hi there! 
Fix for #542 
Fix for #541 
Decided to do both parts of the issue since they both significantly improve UX. 
1. Fixed the function of naming created duplicate snippets. Now the function will not duplicate the infinite insertion of “-copy”, and will take into account the number of copies. 
2. Also I added tooltips for hovering on snippet cards. There is it's looks like
> [#542]: Add numbering of copies and tooltips for hovering snippet cards

- frontend/src/components/Modals/NewSnippet.jsx
- frontend/src/locales/en.json
- frontend/src/locales/ru.json
BUG #564 
- added java language to i18next locales to fix java icon appearance
- fixed handleInputLng() function at NewSnippet.jsx
while testing the code, i've discovered a new bug at modal on new snippet selection:
inside modal we cannot select "java" option because of this block:
```javascript
const filteredOptions = supportedLanguages.filter((language) =>
language.toLowerCase().startsWith(inputValue.toLowerCase()),
);
setSelectedLng(filteredOptions.slice(0, 1));
```
when we type "java" the filteredOptions will filter all occurences which starts from "java". It means option "javascript" has been included. Array will become like this:
```javascript
const filteredOptions = ['javascript', 'java'];
// filteredOptions.slice(0, 1) = 'javascript';
setSelectedLng('javascript');
```
at my …
> #564 bug at new snippet selection

- backend/package.json
- backend/src/entities/user-settings.entity.ts
- backend/src/main.ts
- backend/src/migrations/1730013613468-backend_user_settings.ts
- backend/src/users/dto/update-user-settings.dto.ts
- backend/src/users/users.service.ts
- frontend/package.json
- frontend/src/components/Forms/AvatarChangeForm.jsx
- frontend/src/components/Modals/ChangeAvatar.jsx
- frontend/src/components/Modals/RemoveAvatar.jsx
- frontend/src/components/Navigation/UserMenu.jsx
- frontend/src/pages/profile/index.jsx
- frontend/src/slices/index.js
- frontend/src/slices/userSettingsSlice.js
- yarn.lock
#546 
Загружаем и конвертируем аватар из jpg/jpeg, bmp, png в jpeg 250px x 250px, сохраняем в формате base64 в таблице user-settings, храним состояние в userSettingsSlice. После конвертации размер картинки не превышает 250kb-300kb.
https://github.com/user-attachments/assets/27590085-c891-4db7-bf1b-909cea5b07c7
> Adding an avatar by an authorized user

- frontend/src/components/Forms/GithubSignInButton.jsx
The problem was this: When you click the "Try without registration" button, guest data was added to the browser local storage. Then, when you click the login via github button, the guest data was not deleted from the local storage. And this led to the user menu not being displayed correctly in the navigation bar. I added a handler for clicking the login via github button, which deletes the guest data from the local storage. Perhaps this is not the best solution. If so, please provide comments on how you would like to see the implementation of deleting guest data from the local storage. Perhaps this is an architectural issue and fixing a user as a guest or as an authorized user should be done through the state manager (redux), and not through the browser's local storage. Please clarify.
> Remove guestUserData from localStorage on GitHubSignInButton click

- frontend/src/pages/snippet/index.jsx
* ### Фон теперь устанавливается только для HTML-сниппетов, что предотвращает проблемы с видимостью текста при переключении тем / Backgrounds are now only set for HTML snippets, preventing text visibility issues when switching themes
* ### Установлен белый фон для HTML-сниппетов, чтобы текст всегда оставался видимым при переключении между светлой и темной темами / Set a white background for HTML snippets so that the text always remains visible when switching between light and dark themes
> Fix issue #524: исправлено отображение HTML-сниппетов в темной теме

- frontend/src/components/Modals/NewSnippet.jsx
Доделал [issue #564](https://github.com/hexlet-rus/runit/issues/564) - увеличил количество отображаемых  языков в popup окне. 
В процессе правки обнаружил потенциальный баг:
1.  Заходим в модальное окно по кнопке "Try without registration"  
2. Выбираем язык
3. После этого пытаемся в строке ввода языка поправить, нажимаем либо del либо backspace - сайт падает с белым экраном. Ошибки на прикладываемом видео.
https://github.com/user-attachments/assets/540c3a7f-30a8-4746-81d3-61e4c8af6be3
Баг поправил - в handleInputLng() сделал дефолтное значение для аргумента (пока кроме пустой строки ничего дельного не придумал), чтобы не передавалось undefined.
[деплой](https://ja-ru-runit.onrender.com/)
> fix: pop up menu in newSnippet modal
