hexlet-rus/runit

app/assets/index.html, app/javascript/App.jsx, app/javascript/Pages/Profile.jsx, app/javascript/Pages/Profile.module.css, app/javascript/components/Button/Button.module.css, app/javascript/components/Button/hooks.js, app/javascript/components/Button/index.jsx, app/javascript/components/Modals/GetLink.jsx, app/javascript/components/Modals/Info.jsx, app/javascript/components/Modals/Modal.jsx, app/javascript/components/Modals/SaveRepls.jsx, app/javascript/components/Modals/SignIn.jsx, app/javascript/components/Modals/SignUp.jsx, app/javascript/components/Navbar.jsx, app/javascript/components/Terminal/index.jsx, app/javascript/hooks/index.js, app/javascript/locales/ru.js, app/javascript/providers/AuthProvider.jsx, app/javascript/providers/SnippetsProvider.jsx, src/snippets/snippets.controller.spec.ts
- Added and stylized profile page
- Updated snippet name validation
- Updated user login status checking
- Updated locales and texts
- Added snippet extension autocomplete
add #4
=> Profile page

app/javascript/components/Navbar.jsx, app/javascript/providers/AuthProvider.jsx
Починил кнопку разлогинивания, при нажатии на которую не происходило разлогинивания
=> fix logout button

app/javascript/components/Modals/NewRepl.jsx
#26 Изначально хотел сделать настройку минимальной и максимальной длины генерируемого слова через передачу объекта options внутрь faker.word.adjective(), но по какой-то причине установленные параметры полностью игнорируются. Даже пример из документации не заработал...
=> Add snippet name generation

app/javascript/Pages/Profile.jsx, app/javascript/Pages/SignUp.jsx, app/javascript/providers/SnippetsProvider.jsx
- added function to delete snippets
- added notification about existing user when registering
- added deletion handler
enhancement #25
=> snippet deletion functinality

app/javascript/Pages/SignUp.jsx, app/javascript/locales/ru.js, src/entities/user.entity.ts, src/migrations/1663236009774-migration.ts, src/users/dto/create-user.dto.ts, src/users/dto/update-user.dto.ts, src/users/users.controller.spec.ts, src/users/users.module.ts, src/users/users.service.ts, src/users/validation/check-login.ts, src/users/validation/check-name.ts
#23 
подправил тексты
добавил валидацию на уникальность логина
=> Change name field

app/assets/robots.txt, views/landing/landing-editor.pug
* Еще добавил файл robots.txt из этой [задачи](https://github.com/Hexlet/runit/issues/41)
=> [#40] Replace tags on landing

src/entities/user.entity.ts, src/migrations/1663236009774-migration.ts
Поправил ошибку 500 при регистрации пользователя на продакшене, PostGreSQL воспринимал тип данных character, как varchar(1), может быть ключом к решению #43
=> fix postgres

app/javascript/Pages/Profile.jsx, app/javascript/components/Modals/Modal.jsx, app/javascript/components/Modals/RenameRepl.jsx, app/javascript/providers/SnippetsProvider.jsx, app/javascript/slices/index.js, app/javascript/slices/snippetsSlice.js
=> Added the ability to rename a snippet

app/javascript/components/Embed/EmbedSnippet.jsx
При клике на иконку открывается новая вкладка.
Issue: https://github.com/Hexlet/runit/issues/73
=> Fix button in iframe

app/javascript/Pages/SignIn.jsx, app/javascript/Pages/SignIn.module.css, app/javascript/Pages/SignUp.jsx, app/javascript/Pages/SignUp.module.css
Скорректировал по данному issue: https://github.com/Hexlet/runit/issues/60
=> login and signup interfaces moving when error messages appearing

views/landing/landing-editor.pug
Добавил отступы https://github.com/hexlet-rus/runit/issues/99
=> fix: indents on landing page

app/javascript/components/Navbar.jsx
=> fix navbar logo display

app/assets/landing/styles/style.css, app/javascript/components/Faq.jsx, views/landing/modules/faq.pug
Обновил стили согласно референсной страницы /about 
issue #107
второй коммит: добавил отступ для faq
=> update accordion style on landing page

__fixtures__/testData.json, __tests__/users.e2e-spec.ts, app/javascript/components/Modals/ChangePassword.jsx, app/javascript/components/Modals/EditProfile.jsx, src/entities/user.entity.ts, src/users/dto/create-user.dto.ts, src/users/dto/update-user.dto.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts, src/users/validation/check-login.ts, src/users/validation/check-password.ts
Сделал необходимые проверки на бекенде при смене пароля и изменения пользователя и добавил изменения на фронте под эти изменения
=> Update user data and change password at backend

app/javascript/AppRoutes.jsx, app/javascript/locales/en.js
@dzencot еще раз привет!
сейчас пытался локально развернуть проект, но этого не происходило из-за 2 ошибок в коде.
=> Locales hotfix

app/javascript/App.jsx, app/javascript/components/Button/hooks.js, app/javascript/components/Embed/EmbedSnippet.jsx, app/javascript/components/Repls/index.jsx, app/javascript/locales/en.js, app/javascript/locales/ru.js, app/javascript/slices/editorSlice.js
=> Show the current saving status of the snippet. Closes #28

app/javascript/Pages/Landing/Landing.jsx, app/javascript/components/Footer.jsx, app/javascript/components/Navbar.jsx
Поменял обычные ссылки на ссылки от роутера, так как приложение не работало как SPA, плюс немного поправил верстку на лёндинге
=> hotfix links in  Navbar and Footer

app/javascript/locales/en.js, app/javascript/locales/ru.js
Изменение текста выводимой ошибки валидации при регистрации - в поле Логин. Поясняющее требования к формату Логина
=> Validation text update

.github/ISSUE_TEMPLATE/bugreport.yml
=> add bug issue template

frontend/src/components/Footer.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js
=> footer add source code

.github/ISSUE_TEMPLATE/featureRequest.yml
add feature request-issue-template
=> add feature request-issue-template

.github/ISSUE_TEMPLATE/task.yml
=> add task issue template

frontend/src/Pages/RemindPassword.jsx
=> fix issue-179

frontend/src/Pages/RemindPassword.jsx
=> fix issue 178

frontend/src/Pages/SignIn.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js
Добавил полю "Электронная почта" дополнительную валидацию в formik, использовав библиотеку Yup. Теперь поле "Электронная почта" подсвечивается красным при вводе некорректной почты.
=> [#183] fix incorrect email field feedback bug

frontend/src/Pages/Profile.jsx, frontend/src/components/Modals/NewRepl.jsx, frontend/src/slices/snippetsSlice.js, frontend/src/slices/userSlice.js
=> Fix snippets duplicate bug

backend/src/snippets/snippets.controller.ts, backend/src/snippets/snippets.service.ts, frontend/src/App.jsx, frontend/src/AppRoutes.jsx, frontend/src/Pages/Profile.jsx, frontend/src/components/Editor/index.jsx, frontend/src/components/Embed/EmbedSnippet.jsx, frontend/src/components/Modals/NewRepl.jsx, frontend/src/components/Modals/ShareRepl.jsx, frontend/src/components/SnippetButton/index.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js, frontend/src/providers/SnippetsProvider.jsx, frontend/src/routes.js, frontend/src/slices/editorSlice.js, frontend/src/slices/terminalSlice.js
=> Fix snippet links

frontend/src/components/Embed/EmbedSnippet.jsx
=> Fix snippet loading

frontend/src/locales/ru.js
Удалил слово "бесплатный" в frontend/src/locales/ru.js
remindPass.footer.signUp
signIn.footer.signUp
=> Не корректный текст "Создать бесплатный аккаунт"

frontend/src/application.jsx
Переопределить метод yup.string.email согласно инструкции из readme yup
=> Fix email validation

frontend/src/components/Navbar.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js
Add "editor" link to the Navbar as per issue description.
=> Update Navbar links to contain "editor" when user is logged in

frontend/src/Pages/SignIn.jsx
Скрыл ссылку [Не помню пароль](https://runit.hexlet.ru/remind_password) на странице входа.
Временная мера по причине того, что восстановление пароля пока не работает.
=> Temporarily hide password reset link

backend/package.json, backend/src/main.ts, yarn.lock
https://fey-runit.onrender.com/api
=> add swagger

backend/src/config/mailer.config.ts, backend/src/users/dto/recover-user.dto.ts, backend/src/users/users.service.ts
на Heroku добавил нужную переменную окружения. 
Поправил емейл From 
Убрал дублирование
=> Add sparkpost

frontend/src/Pages/SignUp.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js
Now you can enter letters, numbers, and special characters without spaces in the login field
=> Fixes #240

backend/.eslintrc.yml, backend/src/auth/auth.controller.ts, backend/src/config/data-source.config.ts, backend/src/migrations/1682678760453-fill-null-slugs-snippets.ts, backend/src/snippets/snippets.service.ts, backend/src/snippets/utils/generate-uniq-slug.ts, backend/src/users/dto/create-user.dto.ts
#237 Добавил миграцию для заполнения null значений слага у сниппетов, вынес генерацию слага в отдельную утилиту
=> added migration to fill null values for slugs

frontend/src/Pages/Profile.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js
Delete button "Copy link" from Profile.jsx. Delete "copyProfileButton" from locales.
=>  [#259] Update Profile.jsx

README.md, README.ru.md
Исправила грамматические, стилистические ошибки. Привела файлы к соответствию друг с другом.
=> [#273] Update files to match

frontend/src/components/Navbar.jsx, frontend/src/routes.js
Добавил редирект на  по клику на логотип. Если пользователь зарегистрирован, то по клику на логотип - переходим на страницу профиля, если не зарегистрирован - переходим на лендинг.
=> Redirect by clicking on the logo

frontend/src/providers/AuthProvider.jsx
При нажатии на кнопку выхода, перекидывало на страницу редактора кода /editor, а не на корневую. 
Так и было по задумке? Если нет, поправил :)
=> fix logout

frontend/src/Pages/SignIn.jsx, yarn.lock
Уведомление о неправильном логине или пароле теперь отображается в отдельной плашке под полями, при этом сами поля не подсвечиваются красным (чтобы сохранить подсветку полей только в случае некорректных данных)
=> Fix signIn error message

frontend/src/Pages/SignIn.jsx, frontend/src/Pages/SignUp.jsx
Исправил ошибки, которые были вызваны конфликтом веток
=> fix conflicts

frontend/src/Pages/SignIn.jsx, frontend/src/Pages/SignUp.jsx, frontend/src/locales/en.js, frontend/src/locales/ru.js, frontend/src/utils/validationSchemas.js
1. Возвращает частично потерянные изменения из ПР https://github.com/hexlet-rus/runit/pull/286 и https://github.com/hexlet-rus/runit/pull/290
2. Удаляет дубликаты сообщений в русской локали и переименовывает некоторые ключи (correctEmail в incorrectEmail)
3. Убирает ненужный вызов функции t из i18n в файле со схемами валидации
=> Fix previous conflict resolving

frontend/src/AppRoutes.jsx, frontend/src/routes.js
=> Fix routes profile

frontend/src/components/Footer.jsx
Заменил нерабочую ссылку на новую
=> #313 fix wronk url in link

static.json
Обновил static.json
возможно проблема была в том, что было явно не указано, куда смотреть и куда перенаправлять.
=> #303 updated static.json

frontend/src/components/Forms/SignInForm.jsx, frontend/src/utils/validationSchemas.js
=> added password validation in SignInForm

tests/workflow.spec.ts
Проверил локально и линтер и работу тестов, все ок)
=> [#177] write tests allure ids 301, 332, 333, 334

frontend/src/AppRoutes.jsx, frontend/src/locales/en.js
Добавлено отображение спиннера при загрузке страниц со слабым интернетом.
=> [#309] add loading spinner

frontend/src/components/Forms/SignInForm.jsx, tests/workflow.spec.ts
Линтер без ошибок, в тестах локально есть ошибки, не пойму почему.
В первый раз в проде они исчезли, возможно, сейчас тоже так отработает.
=> [#177] write tests allure ids 364, 366, 367

frontend/src/components/Forms/SignInForm.jsx, package.json, tests/workflow.spec.ts
Изменил команду запуска e2e тестов в package.json
=> Test start

README.md, README.ru.md
=> Add instructions for setting up OAuth

frontend/src/pages/profile/SnippetCard.jsx, frontend/src/pages/snippet/FileToolbar.jsx
Предупреждение при переименовании снипета в общем меню
-----
Предупреждение при переименовании снипета внутри компонента
----
=> [#378] fix error msg edit snippet name

frontend/src/components/Forms/SignInForm.jsx
Моя попытка 2)
добавила ссылку "не помню пароль".
До:
После:
=> [#381] added link to forgot Password in Forms/SignInForm.jsx

frontend/src/locales/en.json, yarn.lock
=> fix typo 'sign in' button

frontend/src/AppRoutes.jsx, frontend/src/utils/scrollToTop.js
Вот этот ишью: https://github.com/hexlet-rus/runit/issues/392
Использовал компонент React Router из документации: https://v5.reactrouter.com/web/guides/scroll-restoration
=> Add functionality where the page would not scroll up when navigating between pages.

frontend/package.json, frontend/src/components/Modals/NewSnippet.jsx, frontend/src/components/Modals/index.jsx, frontend/src/components/Navigation/UserMenu.jsx, frontend/src/locales/en.json, frontend/src/locales/ru.json, tests/workflow.spec.ts, yarn.lock
https://runit-opensource-pd4i.onrender.com/
=> #387 add modal for create new snippet

frontend/src/components/Navigation/UserMenu.jsx
Hide share tab in user menu.
https://github.com/hexlet-rus/runit/issues/423#issuecomment-1936111272
Render deploy: https://bobronaud-runit-423.onrender.com
=> closed #423

frontend/package.json, frontend/src/components/Forms/AvatarChangeForm.jsx, frontend/src/components/Modals/ChangeAvatar.jsx, frontend/src/components/Modals/RemoveAvatar.jsx, frontend/src/components/Modals/index.jsx, frontend/src/locales/ru.json, yarn.lock
реализовал два компонента для разных модальных окон: для загурзки аватара и для удаления оного
т.к. серверная часть не реализована - сделал с локальным состоянием, чтобы можно было протестировать работу
не получилось сделать деплой всего проекта, чтобы показать, поэтому ниже пример-гифка 😄
=> [#418] create two modals: to upload user avatar, to delete user avatar, create locales for both modals

frontend/src/components/Modals/NewSnippet.jsx
Добавил возможность создавать новый сниппет по HTML шаблону
Deploy: https://bobronaud-runit-2.onrender.com
=> Closed #432

frontend/src/assets/stylesheets/toolbar.scss
для свойства flex-flow указано значение row wrap
деплой https://vyacheslav-pv-runit.onrender.com/
=> [#444] fix toolbar

frontend/src/pages/profile/SnippetCard.jsx
Добавил класс d-none кнопкам футера в случае если toolbar скрыт
=> [#448] added classes d-none for snippet card footer buttons

frontend/src/components/Navigation/index.jsx
=> fixed dropdown on mobile

frontend/src/assets/stylesheets/application.scss, frontend/src/pages/landing/Header.jsx
=> Fix bootstrap style

frontend/src/components/Footer/index.jsx, frontend/src/locales/ru.json
#485 fix footer
У меня на рендере закончился период для инстанса, поэтому прикладываю изображение. Но если будет недостаточно, то сделаю новый аккаунт
=> Fixed tg footer

frontend/src/pages/landing/Footer.jsx
=> fix footer landing

frontend/src/components/Modals/DuplicateSnippetModal.jsx, frontend/src/pages/profile/SnippetCard.jsx, frontend/src/pages/snippet/ActionsToolbar.jsx
Починила баг с некорректным выбором текущего языка при создании копии сниппета.
Деплой по ссылке: https://heaven-tonight-runit-4cg0.onrender.com
=> [#483] fixed duplicate snippet bug

frontend/src/pages/landing/Landing.jsx, frontend/src/pages/landing/landing.scss
Исправил проблему с багом в #458 
Убрал класс темной темы, когда активируется светлая тема
=> fix text showing in landing when dark theme is activated

frontend/src/components/Forms/AvatarChangeForm.jsx, frontend/src/components/Modals/ChangeAvatar.jsx, frontend/src/components/Modals/NewSnippet.jsx, frontend/src/components/Modals/RemoveAvatar.jsx, frontend/src/components/Navigation/UserMenu.jsx
=> [#495 fix warning]

frontend/src/AppRoutes.jsx
Добавлен редирект с лендинга главной страницы приложения в профиль пользователя, если тот авторизован.
#492
=> Redirect auth users to snippets

frontend/src/pages/landing/Footer.jsx
Исправил ошибки из #511 и немного изменил отображение футера, сделав его более компактным
=> #511 Footer fix

frontend/src/pages/landing/Landing.jsx
#458 исправление цвета заднего фона.
Ранее эта ветка была тут #491
=> Fixed rowClass

frontend/src/pages/landing/Landing.jsx, frontend/src/pages/landing/landing.scss, yarn.lock
fixed styles for main bg and title
=> [#518] fixed styles for main bg and title

frontend/src/pages/landing/Footer.jsx, frontend/src/pages/landing/landing.scss
Fixed the menu in the footer on Mobile version. Now it appears as it should. Screenshot below for reference.
=> [#523]: fixed footer menu not appearing on mobile version

frontend/package.json, frontend/src/components/Footer/index.jsx, yarn.lock
Hi there! 
Fixes #558 
This PR fixes Footer logo and additionally align of VK logo.
This is what it looks like now
=> [#558]: Fix old Twitter logo in the Footer

frontend/src/assets/stylesheets/min-w.scss, frontend/src/pages/snippet/FileToolbar.jsx
=> #568 set min width on snippets name input

frontend/src/assets/stylesheets/editor-page.scss
Improvement of scss code in order to solve the bug  #526
=> fixing bug panel-handler

frontend/src/locales/ru.json
insignificant misprint corrected / pyhton -> python
=> misprint fix

backend/src/runner/JavaScriptRunner.ts, yarn.lock
- Добавлено ограничения времени выполнения скрипта в 5000 мс и обработка ошибки.
=> Fix javascript runner

backend/src/admins/exceptions/http-exceptions.filter.ts, backend/src/admins/snippets.controller.ts, backend/src/admins/users.controller.ts, backend/src/admins/views/errors/401.pug, backend/src/admins/views/errors/403.pug, backend/src/admins/views/errors/500.pug, backend/src/admins/views/errors/layoutErrors.pug, frontend/src/components/Navigation/AdminPanelButton.jsx
- Исправлена некорректная работа кнопки для перехода в админ панель.
- Добавлен http exceptions для перехвата и обработки ошибок админ панели.
- Добавлены шаблоны pug вывода ошибок (401, 403, 500) в админ панели.
- Добавлена типизации Request в контроллерах users и snippets админ модуля. (При деплое на render сыпались ошибки отсутствующих свойств request)
=> Fix admin section

backend/src/auth/auth.service.ts
- The logic of token creation has been moved from the signin and oAuthGithub methods to the generateJwtToken method.
- Вынесена логика создания токена из методов signin и oAuthGithub в метод generateJwtToken.
=> refactor/generate jwt token.

frontend/.eslintrc.yml, frontend/src/application.tsx, frontend/src/index.js, frontend/tsconfig.json, yarn.lock
Поправил   tsconfig и eslinttrc, теперь на файлы  tsx  не ругается
=> change tsconfig, eslintr support tsx
